Kırık linkler düzeltildi
yazbel/python pull request #14
Opened 2018-07-10 12:20 UTC by hasaser

2018-07-12 06:51 UTC, ismailarilik commented
Ellerinize sağlık. Üç küçük mesele var, bunları düzelttiğinizde merge edeceğim:
- istihza.com'u belgelere yönlendirmek yerine yazbel.com'a yönlendirmek daha mantıklı.
- Linki düzeltirken istihza.com metnini de düzeltmelisiniz.
- Dosya sonuna konulan yenisatırların bu PR'larda olmasına gerek yok.

2018-07-13 00:01 UTC, hasaser commented
Diğer iki sorunu çözdüm ama dosya sonundaki yeni satırdan kastınız ne?

2018-07-13 07:46 UTC, ismailarilik requested changes
Sorunlu kısımlara yorumlar ekledim. Onları düzeltebilir misiniz?

2018-07-13 07:46 UTC, ismailarilik commented on theme/_templates/footer.html
> +</div>
Burada bir yenisatır karakteri var, bunun olmasına gerek yok.

2018-07-13 07:46 UTC, ismailarilik commented on theme/_templates/navigation.html
> +    <li class="depo"><a href="https://yazbel.com">ana sayfa</a></li>
Depo tamamiyle silinebilir.

2018-07-13 07:46 UTC, ismailarilik commented on theme/_templates/page.html
> +<div class='glyph'><a href='https://belgeler.yazbel.com/python-istihza/'>&#x2663;</a></div>
istihza.com, yazbel.com olarak çevrilmeli.

2018-07-13 07:46 UTC, ismailarilik commented on theme/_templates/page.html
> +{% endblock %}
Burada bir yenisatır karakteri var, bunun olmasına gerek yok.

2018-07-13 14:59 UTC, hasaser commented
Yeni satırları ben eklemedim ki. O kendi kendine ekleniyor. Silip tekrar yazmayı sondaki satırı silmeyi denedim ama nedense düzelmiyor

2018-07-14 07:43 UTC, ismailarilik commented
GitHub arayüzünden denedim, dediğiniz gibi oluyor. Siz GitHub arayüzünden mi yapıyorsunuz, yoksa editörden mi? Eğer editörden ise hangi editörü kullanıyorsunuz, ayarlarını kontrol eder misiniz? Eğer EditorConfig kullanıyorsanız, bundan da kaynaklanabilir. Her neyse; merge ediyorum. Teşekkürler.

2018-07-14 07:43 UTC, merged