Tornado yazısındaki eksiklikler giderildi.
yazbel/python pull request #170
Opened 2021-04-18 13:03 UTC by hasaser

Bu sefer düzgün şekilde yaptım.
Bazı hataları düzelttim. Belgelerdeki eksikliği giderdim.

2021-04-19 05:20 UTC, ismailarilik requested changes

2021-04-19 05:20 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/tornado_modülü/tornado_1.rst
> +"Merhaba Zalim Dünya" yazarak başlayalım. Bu iş için `Application'da` olduğu
Burası `Application` olmamalı mı? Yani eskisi gibi.

2021-04-19 10:09 UTC, hasaser commented on sphinx_source/Ucuncu_taraf_moduller/tornado_modülü/tornado_1.rst
> +"Merhaba Zalim Dünya" yazarak başlayalım. Bu iş için `Application'da` olduğu
"`" işareti birçok yerde sıkıntı çıkarttı. Özellikle işaretten sonraki kesme işaretlerinde. Kendinden sonra kesme işareti gelenler çalışmadı. Ben de buna 2 çözüm ürettim. Gerekliyse eki de içeri al, gereksizse sil. O yüzden birçok yerde bu gibi değişiklikler var.

2021-04-20 05:09 UTC, ismailarilik commented
Ne gibi bir sorun çıkardı bu ek? Bu ekten sonra boşluk bırakmak sorunu
çözebilir.

19 Nis 2021 Pzt 13:09 tarihinde hasaser ***@***.***> şunu
yazdı:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In sphinx_source/Ucuncu_taraf_moduller/tornado_modülü/tornado_1.rst
> <https://github.com/yazbel/python-istihza/pull/170#discussion_r615717148>:
>
> > @@ -66,7 +66,7 @@ Sayfa Sunma
>
>  ===========
>
>
>
>  Sitemizde sayfa sunmak için bir view yazmalıyız. Geleneği bozmayalım ve
>
> -"Merhaba Zalim Dünya" yazarak başlayalım. Bu iş için `Application`'da olduğu
>
> +"Merhaba Zalim Dünya" yazarak başlayalım. Bu iş için `Application'da` olduğu
>
>
> "`" işareti birçok yerde sıkıntı çıkarttı. Özellikle işaretten sonraki
> kesme işaretlerinde. Kendinden sonra kesme işareti gelenler çalışmadı. Ben
> de buna 2 çözüm ürettim. Gerekliyse eki de içeri al, gereksizse sil. O
> yüzden birçok yerde bu gibi değişiklikler var.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/yazbel/python-istihza/pull/170#discussion_r615717148>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEGFHYODC3SSMXXCNASEQPDTJP6OJANCNFSM43EGOKTA>
> .
>

2021-04-21 00:37 UTC, hasaser commented
![image](https://user-images.githubusercontent.com/29119741/115480223-be615580-a252-11eb-8b77-6608a753d0a6.png)
Buradaki gibi beklemediğim birkaç yerde karşılaştım bu hatayla. Ben de bu işaretin kullanımını azaltarak çözdüğüme inanıyorum.

2021-04-21 05:17 UTC, ismailarilik commented
Gereksiz yerlerde kaldırılabilir, gerekli yerlerde de ilk tikten önce ve
son tikten sonra boşluk konularak sorun çözülebilir bence.

21 Nis 2021 Çar 03:37 tarihinde hasaser ***@***.***> şunu
yazdı:

> [image: image]
> <https://user-images.githubusercontent.com/29119741/115480223-be615580-a252-11eb-8b77-6608a753d0a6.png>
> Buradaki gibi beklemediğim birkaç yerde karşılaştım bu hatayla. Ben de bu
> işaretin kullanımını azaltarak çözdüğüme inanıyorum.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/yazbel/python-istihza/pull/170#issuecomment-823693136>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEGFHYJHWL5LOEIIG3VPFXLTJYM5RANCNFSM43EGOKTA>
> .
>

2021-04-25 11:06 UTC, hasaser commented
Ben yaptığım değişikliğin sorunu çözdüğünü düşünüyorum. Siz çözmediğini düşünüyorsanız sizin dediğinizi yapayım.

2021-09-20 08:38 UTC, woosal1337 approved these changes

2021-09-29 21:03 UTC, EkremDincel commented on sphinx_source/Ucuncu_taraf_moduller/tornado_modülü/tornado_1.rst
> +"Merhaba Zalim Dünya" yazarak başlayalım. Bu iş için `Application'da` olduğu
@hasaser Tarnoda dökümanlarına göz attım, problem kesme işaretinin kullanılmasından ziyade kullanılmamasından kaynaklı gibi duruyor. Şu gibi bir kullanımda problem yaşamazsınız:
```
`Application`'da
```
Ama bu kullanımı her yerde uygulamanız lazım, bir yerde kesme işareti koyup bir yerde koyulmazsa da sıkıntı çıkıyor.

2021-10-01 06:02 UTC, closed without merging