üreteç ciktisi modifikasyonu [ileri_fonskiyonlar]
yazbel/python pull request #177
Opened 2021-09-23 11:45 UTC by woosal1337

bu [dosyada](https://github.com/yazbel/python-istihza/blob/master/_sources/ileri_fonksiyonlar.rst.txt), satir 2020:

kitapta olan:
```
    >>> üreteç = (i for i in range(5))
    >>> for i in üreteç:
            print(i)
    1
    2
    3
    4
    >>> for i in üreteç:
            print(i)

    >>>
```

olmasi gereken kodun ciktisi:
```
    >>> üreteç = (i for i in range(5))
    >>> for i in üreteç:
            print(i)
    0
    1
    2
    3
    4
    >>> for i in üreteç:
            print(i)

    >>>
```

olmasi gerekiyor. loop'un ilk kismindaki 0 ilk iterationda yazilmamis.

![cikti](https://user-images.githubusercontent.com/69302858/134500436-8efbd84d-cd93-40f6-b878-b4887097fcaa.png)

2021-09-24 07:12 UTC, ismailarilik requested changes

2021-09-24 07:12 UTC, ismailarilik commented on sphinx_source/ileri_fonksiyonlar.rst
> +    0
Aşağıdaki sayılar ile aynı hizada olmamış sanki.

2021-09-26 13:54 UTC, woosal1337 commented on sphinx_source/ileri_fonksiyonlar.rst
> +    0
[cikti modifikasyon 2.0](https://github.com/yazbel/python-istihza/pull/177/commits/4be038c3f7ec74908495a311cc7070f10beed3da)'da bu sorunu halletmeye calistim.

2021-09-26 14:47 UTC, ismailarilik requested changes

2021-09-26 14:47 UTC, ismailarilik commented on sphinx_source/standart_moduller/regex.rst
> +    >>> for i in liste:
Bu dosyadaki değişiklikler daha önce başka bir PR'da yapılmıştı yanlış hatırlamıyorsam. Önemli değil ama bir conflict var, onun çözülmesi gerekiyor, bu sebeple olabilir.

2021-09-26 16:00 UTC, woosal1337 commented
@ismailarilik burada cakisma oldugu icin, en son versiyonu uzerinden yeni pull request olusturdum
[Pull 179](https://github.com/yazbel/python-istihza/pull/179)

2021-09-26 16:00 UTC, closed without merging