f-string kullaniminin detaylandirilmasi
yazbel/python pull request #203
Opened 2022-10-08 19:35 UTC by ahmetveburak

Kisa bir sekilde ozetlemeyi dusunuyordum fakat dokumani da kontrol edeyim derken umarim uygun bir sekilde anlatabilmisimdir.

Dokuman cok detayli o sebeple daha cok ornek kullanarak ozetlemeye calistim
https://docs.python.org/3/library/string.html#format-string-syntax

2022-11-04 12:19 UTC, EkremDincel requested changes
Katkılarınız için teşekkürler. Değindiğim birkaç problem var, bir de conflict'ler var gibi duruyor. Onların düzeltebilirseniz iyi olur.

2022-11-04 12:19 UTC, EkremDincel commented on source/fstring.rst
> -Bu örnekte f-string'imizin normal bir karakter dizisinden farkı yok gibi görünüyor. Aslında şuanlık bir farkı yok. Çünkü biz **f-string**'in özelliklerini henüz kullanmadık. Yukarıda format() fonksiy
Kod örneklerinin öncesindeki paragrafların sonunda `::` bulunması gerekiyor. Aksi takdirde kodlar düzgün renklenmiyor. [BUILDING.md](https://github.com/yazbel/python-istihza/blob/master/BUILDING.md) dosyasını takip ederseniz belgelerin yazıldığı format hakkında bilgi var.

2022-11-04 12:19 UTC, EkremDincel commented on source/fstring.rst
> +        >>> isim = 'Buğra'
`>>>`'ların sebebini anlamadım. Aşağıdakiler ile aynı olsun diye mi?

2022-11-04 12:19 UTC, EkremDincel commented on source/fstring.rst
> +f-string Formatlama Ozellikleri
"Ozellikleri"nin Ö ile başlaması lazım.

2022-11-04 12:19 UTC, EkremDincel commented on source/fstring.rst
> +.. code-block:: text
Burası dokümanın geneline kıyasla ağır olmuş sanki. Daha önce syntax'ı bu şekilde tarif eden bir örnek hatırlamıyorum. Bu kısmı kaldırıp ileri okuma amaçlı resmi dokümana yönlendirmek daha doğru olur kanaatindeyim.

2022-11-04 12:19 UTC, EkremDincel commented on source/fstring.rst
> +f-string içerisinde süslü parantez yazabilmek için genel kaçış karakteri olan ters eğik çizgi (``\``) yerine ``{`` veya ``}`` parantezi 2 defa eklenir.
Yukarıdaki `::` ile alakalı yorumum burada ve alt kısımlarda da geçerli.

2022-11-04 12:25 UTC, EkremDincel commented on source/fstring.rst
> -        print(f'Selam {isim}!')
Kod örneklerinin öncesindeki paragrafların sonunda `::` bulunması gerekiyor. Aksi takdirde kodlar düzgün renklenmiyor. [BUILDING.md](https://github.com/yazbel/python-istihza/blob/master/BUILDING.md) dosyasını takip ederseniz belgelerin yazıldığı format hakkında bilgi var.

2022-11-04 14:52 UTC, ahmetveburak reviewed
Conflict'in sebebini anlamadim inceleyecegim

2022-11-04 14:52 UTC, ahmetveburak commented on source/fstring.rst
> +        >>> isim = 'Buğra'
Evet dokuman butunlugu saglanmasi icin fakat neden hepsine eklemek varken sadece buraya eklemisim hatirlayamadim

2022-11-04 14:52 UTC, ahmetveburak commented on source/fstring.rst
> +.. code-block:: text
Aslinda ben de eklemeyi dusunmuyordum sonra hizimi alamadim :D Dokumana bakip anlamakta zorluk yasayan olursa belki bir nebze anlasilabilir olur diye burada orneklerle birlikte aciklamaya calistim.

2022-11-04 14:52 UTC, ahmetveburak commented on source/fstring.rst
> +f-string içerisinde süslü parantez yazabilmek için genel kaçış karakteri olan ters eğik çizgi (``\``) yerine ``{`` veya ``}`` parantezi 2 defa eklenir.
Bazi yerlerde `.`'dan sonra da `::` ekliyordu. Test ettigim surecte de sorun gormedim diye hatirliyorum ama tekrar ekledim. Dokumani tekrar kontrol ettim `.`'dan sonra bir bosluk birakinca `:` ekleme yapmiyormus o da hallolmus oldu.

2022-11-04 14:52 UTC, ahmetveburak commented on source/fstring.rst
> +f-string Formatlama Ozellikleri
Tesekkurler gozumden kacmis

2022-11-04 17:42 UTC, ahmetveburak commented on source/katkida_bulunanlar.rst
> +===============
Benimle ilgili bir konu degil fakat `=` sayisi yeterli olmadigi icin warning veriyordu. Sanirim o yuzden suan baglanti olusturmuyor. Isterseniz geri alabilirim.

2022-11-04 17:50 UTC, ahmetveburak commented
@EkremDincel 
Bazi dosyalarda ayni icerik olsa da bosluklar veya html taglari farklilik gosteriyor, sebebini biliyor musunuz?

2022-11-14 09:10 UTC, EkremDincel commented on source/katkida_bulunanlar.rst
> +===============
Yok, böyle olması lazım zaten. Daha önce gözden kaçmış.

2022-11-14 09:12 UTC, EkremDincel commented
@ahmetveburak Ne demek istediğinizi tam anlamadım. .rts`` dosyalarının içeriği aynı olduğu halde üretilen HTML'lerde farkların olduğunu söylüyorsanız Sphinx inşa sürecinde herhangi bir problem vermiyorsa bu önemli değil.

2022-11-14 09:16 UTC, ahmetveburak commented
Suradaki durumu kastetmistim @EkremDincel 
Isaretli olan ve alttaki bir kac satir
https://github.com/yazbel/python-istihza/pull/203/files#diff-24a369aad5ed2990c18f432699e9c9c12e9d81b9eb98f1b1e1fe2b81d363b633L142

2022-11-14 09:26 UTC, EkremDincel commented
Yeni eklenen taglara bakarsanız kod kısmı renklenmiş. Eski halinde düzgün renklenmiyormuş demek ki. [Şu](https://github.com/yazbel/python-istihza/commit/927192b37ceca7f47ec142badef3fe6ad4296c24) commit'teki düzeltme `docs/_sources`'e yeni yansımış. Niye yeni yansımış anlamadım ama `_sources` dizini zaten Sphinx tarafından yönetiliyor, sıkıntı olacağını sanmıyorum.

2022-11-14 09:28 UTC, EkremDincel commented
Şimdi yansımasının sebebi build'in yeni commit edilmesi imiş. Bu değişikliği ilk build eden sizsiniz.

2022-11-14 09:37 UTC, EkremDincel commented on source/fstring.rst
> +String nedir hepimiz biliyoruz, Türkçeye karakter dizisi olarak çeviriyoruz. Bu yapıya da f-string diyoruz çünkü bu yapıyı kullanmak istediğimiz stringin (karakter dizisinin) başına **f** veya **F**
Şimdi dökümanın [şu anki haline](https://python-istihza.yazbel.com/fstring.html) göz attım da dikkat ederseniz `belirtiyoruz.::` kısmı `belirtiyoruz.:``şeklinde yansımış. Normalde koddan önceki cümlelerin sadece `::` ile bitmesi lazım ki `belirtiyoruz:` gibi bir metin oluşsun. Bu tür yerlerde noktayı silip boşluk bırakmadan `::`  yazabilirsiniz.

2022-11-14 09:42 UTC, EkremDincel commented on source/fstring.rst
> +String nedir hepimiz biliyoruz, Türkçeye karakter dizisi olarak çeviriyoruz. Bu yapıya da f-string diyoruz çünkü bu yapıyı kullanmak istediğimiz stringin (karakter dizisinin) başına **f** veya **F**
``. ::`'ları `::` ile değiştirirseniz bir problem kalmayacak.

2023-06-08 17:05 UTC, EkremDincel commented
Katkılarınız için teşekkürler.

2023-06-08 17:05 UTC, merged