İmla hataları
yazbel/python pull request #33
Opened 2018-10-28 03:08 UTC by dotw666

2018-10-28 09:42 UTC, ismailarilik commented on sphinx_source/sozluklerin_metotlari.rst
> +boşaltabiliriz::
Bu, gerekli bir düzeltme değil. Bu değişikliği silebilir misiniz?

2018-10-28 09:42 UTC, ismailarilik requested changes

2018-10-28 09:42 UTC, ismailarilik commented on sphinx_source/sozluklerin_metotlari.rst
> +boşaltabiliriz::
Bu, gerekli bir düzeltme değil. Bu değişikliği silebilir misiniz?

2018-10-28 21:07 UTC, dotw666 commented on sphinx_source/sozluklerin_metotlari.rst
> +boşaltabiliriz::
Konuda anlatilan sanirim 7. metod. o yuzden silinmesi gerektigini dusundum. Anladigim kadari ile Kumeler konusundan aynen alinti yapilmis. Kumeler konusunda ayni baslik ilk sirada

2018-10-29 08:20 UTC, ismailarilik commented on sphinx_source/sozluklerin_metotlari.rst
> +boşaltabiliriz::
Aslında ilk baştaki listede en başta clear metodu geliyor. Belki açıklama başlıkları da bu sıraya göre dizilebilir.

2018-11-27 07:29 UTC, merged