kivy dersleri eklendi
yazbel/python pull request #36
Opened 2018-11-18 09:56 UTC by coderistan

2018-11-19 19:24 UTC, ismailarilik requested changes

2018-11-19 19:24 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +#################################
Başlığı işaret eden karakterler (burada `#`) başlık karakter sayısından fazla (Burada 7 tane olmalı.).

2018-11-19 19:24 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +Olaylardan önceki bölümlerde bahsetmiştik, ancak detaylı olarak anlatmamıştık. Bu bölümde Olaylar'dan biraz daha detaylı bir şekilde bahsedeceğiz. Öncelikle olay nedir tanımlamaya çalışalım. Bir olay
"Olaylar'dan" -> "olaylardan" olmalı (küçük harf)

2018-11-19 19:24 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +=====================
- 'Clock Events' -> 'Clock Olayları' ya da 'Saat Olayları' (Bağlama göre siz karar verin.)
- Başlığı işaret eden karakterler (burada =) başlık karakter sayısından fazla.

2018-11-19 19:45 UTC, coderistan commented
Hatalar düzeltildi. Gözden kaçmış başka hatalar varsa bildirin lütfen

2018-11-20 07:30 UTC, ismailarilik requested changes

2018-11-20 07:30 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +Input Events
'Input Events' -> 'Girdi Olayları'

2018-11-20 07:30 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +Input Events
Diğer başlıklara bakmadım; benzer sorun varsa, düzeltebilir misiniz?

2018-11-20 07:30 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +==================
Başlık altı karakterler fazla. Diğer başlık altı karakterlerden sorun olanları da düzeltebilir misiniz?

2018-11-20 07:30 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/events.rst
> +==================
Aslında çok önemli değil ancak inşa sırasında uyarı veriyor. Bu arada belgelerinizi, göndermeden önce inşa (build) ettiniz mi?

2018-11-20 07:30 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/giris.rst
> +###################################
Başlık üstü ve altı karakterler fazla.

2018-11-20 09:44 UTC, coderistan commented
Evet, inşa edip kontrol etmiştim. Ancak kullandığım sphinx sürümünde bu fazla karakterler için hata vermedi. Yine de gördüğüm kadarını düzelttim.

2018-11-21 05:20 UTC, ismailarilik commented
Sphinx'in son sürümünü kullandığınıza emin olun. Ubuntu kullanıyorsanız en son sürüm apt paketini kurmanız yeterli.

2018-11-21 05:29 UTC, ismailarilik requested changes

2018-11-21 05:29 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/index.rst
> +.. _Github: https://github.com/coderistan/python-istihza
Bu adres YazBel'deki python-istihza'yı işaret etmeli. Çünkü katkıda bulunmak isteyenler sizin veri havuzunuza değil, bu veri havuzuna katkıda bulunacaklar.

2018-11-21 05:29 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/kurulum.rst
> +Burda çok detaylı olarak kurulumu anlatmayacağız. Gerekli linkleri vereceğim, eğer yine de kurulumda sorun yaşarsanız forumda konu açarak belirtebilirsiniz.
'Burda' -> 'Burada'

2018-11-21 05:29 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/kivy_dersleri/layout.rst
> +#####################
Başlık altı ve üstü karakterler fazla.

2018-11-29 11:51 UTC, ismailarilik approved these changes

2018-11-29 12:13 UTC, merged