Colorama ve Pyperclip Modülü eklendi
yazbel/python pull request #48
Opened 2019-04-06 15:15 UTC by erdmykr

Pyperclip ve Colorama modülü eklendi.

2019-04-06 15:50 UTC, ismailarilik requested changes

2019-04-06 15:50 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/index.rst
> +	colorama_modülü/index
Modülleri harf sırasına göre ekler misiniz?

2019-04-15 15:25 UTC, hasaser commented on sphinx_source/Ucuncu_taraf_moduller/index.rst
> +	colorama_modülü/index
Bu gerçekten gerekli mi?

2019-04-15 15:34 UTC, ismailarilik commented on sphinx_source/Ucuncu_taraf_moduller/index.rst
> +	colorama_modülü/index
Gerekli değil ama ulaşılabilirlik açısından daha iyi olduğunu düşünüyorum.

2019-12-25 19:40 UTC, hasaser commented
Ulaşılabilirlik 9 ay boyunca insanların bu bilgiden mahrum kalmasına değer mi?

2020-02-01 20:28 UTC, merged