Linkler Düzeltildi
yazbel/python pull request #58
Opened 2019-06-05 23:10 UTC by HakanDemiral

sadece gerekli olan istihza.com linkleri waybackmachine veri tabanındaki en güncel snapshotları ile güncellendi ve gerekli açıklama linklerin altına yazıldı

2019-06-07 05:38 UTC, ismailarilik requested changes

2019-06-07 05:38 UTC, ismailarilik commented on .gitignore
> +sphinx_source/.DS_Store
Tek ".DS_Store" yeterli olmalı.

2019-06-07 13:27 UTC, HakanDemiral commented on .gitignore
> +sphinx_source/.DS_Store
önerdiğiniz şekilde düzenlenip yorum satırı da eklenmiştir

2019-06-07 20:35 UTC, HakanDemiral commented
yeni değişiklikler ekledim

2019-06-08 07:12 UTC, ismailarilik approved these changes

2019-06-08 07:18 UTC, ismailarilik commented on sphinx_source/karakter_dizilerinin_metotlari3.rst
> +    (İstihza projesi sonlandığı için bu link Wayback Machine tarafından arşivlenen sayfaya yönlendirilmiştir.)
Bundan bahsetmeye gerek olmadığını düşünüyorum. Burada asıl önemli olan ilgili forum gönderisine bu bağlantı aracılığı ile ulaşabilmek. Yukarıya bununla ilgili bir yorum daha ekledim.

2019-06-08 07:18 UTC, ismailarilik commented on sphinx_source/karakter_dizilerinin_metotlari3.rst
> +    <https://web.archive.org/web/20150913015518/http://www.istihza.com/forum/viewtopic.php?f=25&t=63>`_ adresinde şöyle bir
Bağlantının sonuna "(arşiv bağlantısı)" gibi bir ifade konulabilir. Aşağıdaki metinden daha kısa ve öz olur.

2019-06-09 05:39 UTC, merged