f-string dökümanı oluşturuldu ve index dosyasına eklendi.
yazbel/python pull request #6
Opened 2018-05-10 18:29 UTC by bisguzar

2018-05-19 08:52 UTC, ismailarilik commented on sphinx_source/fstring.rst
> +Daha önceki bölümlerde **format()** fonksiyonu karakter dizilerini nasıl biçimlendirebileceğimizi görmüştük. 3.6 sürümü ile Python'a eklenen f-string yapısı da buna benzer bir şekilde çalışıyor. Önce
'fonksiyonu' yerine 'fonksiyonuyla' olmalı.

2018-05-19 08:53 UTC, ismailarilik commented on sphinx_source/fstring.rst
> +Daha önceki bölümlerde **format()** fonksiyonu karakter dizilerini nasıl biçimlendirebileceğimizi görmüştük. 3.6 sürümü ile Python'a eklenen f-string yapısı da buna benzer bir şekilde çalışıyor. Önce
'hatırlayalım.::'daki nokta işareti olmamalı.

2018-05-19 08:54 UTC, ismailarilik commented on sphinx_source/fstring.rst
> +format() fonksiyonumuz kendisine verdiğimiz değerleri kapsama alanı içerisinde uygun yerlere yerleştirir. hatırlarsanız format() fonksiyonunu ilgilendiren kısımları süslü parantezlerin içine yazıyord
'hatırlarsanız' sözcüğü büyük harfle başlamalı.

2018-05-19 08:57 UTC, ismailarilik requested changes
Değerli katkınız için teşekkür ederim. Gecikme için de kusura bakmayın. Belgeleri inşa edebilmem kolay olmadı. Birkaç yerde yazım yanlışları var. Ben bunlardan birkaçını belirttim ama hepsine bakmadım. Belgeyi gözden geçirip bunları düzeltir misiniz?

2018-05-19 08:57 UTC, ismailarilik commented on sphinx_source/fstring.rst
> +Bu sefer format() fonksiyonuna belirli bir yer göstermediğimiz için sırasıyla ilgili alanlara verdiğimiz parametreleri dolduracak. Zaten bir parametre ve bir alan olduğu için yukarıdaki örnekle aynı
'bukadar' sözcük grubundaki 'bu' ve 'kadar' sözcükleri ayrı yazılmalı.

2018-05-19 22:17 UTC, bisguzar commented
"Yazım hataları düzeltildi" konulu commit'de yazım hatası yapmış olmam sizi yanıltmasın, gerçekten düzeltildi :tada:

2018-05-20 09:27 UTC, ismailarilik requested changes

2018-05-20 09:27 UTC, ismailarilik commented on sphinx_source/fstring.rst
> +.. author:: Buğra İşgüzar <biisguzar@gmail.com>
`author` yönergesini aşağıdaki `meta` yönergesi içine yazar mısınız? Sphinx bu şekilde bu yönergeyi tanımıyor.

2018-05-20 09:55 UTC, ismailarilik commented on sphinx_source/fstring.rst
> +.. author:: Buğra İşgüzar <biisguzar@gmail.com>
Tamamdır, işler hızlı yürüsün diye ben değiştirdim.

2018-05-20 09:55 UTC, merged