argparse Modülü eklendi.
yazbel/python pull request #78
Opened 2019-08-22 12:56 UTC by mehmetkiran

2019-08-23 06:23 UTC, ismailarilik requested changes

2019-08-23 06:23 UTC, ismailarilik commented on sphinx_source/standart_moduller/argparse.rst
> +Argparse Modülü
Modülün adı, özel ad olduğu için, olduğu şekliyle yazılmalı: `argparse`

2019-08-24 09:32 UTC, ismailarilik requested changes

2019-08-24 09:32 UTC, ismailarilik commented on sphinx_source/standart_moduller/argparse.rst
> +ArgumentParser Nesnesi
**ArgumentParser Sınıfı** demek gerekmez mi?

2019-08-24 09:32 UTC, ismailarilik commented on sphinx_source/standart_moduller/argparse.rst
> +Temel olarak `ArgumentParser` nesnemizin yapısı::
"`ArgumentParser` sınıfı" demek gerekmez mi?

2019-08-24 09:39 UTC, mehmetkiran commented on sphinx_source/standart_moduller/argparse.rst
> +Temel olarak `ArgumentParser` nesnemizin yapısı::
Metnin orjinalinde 'ArgumentParser objects' olarak geciyor. O sebeplr nesneyi kullandim.

2019-08-25 08:20 UTC, ismailarilik approved these changes

2019-08-25 08:21 UTC, ismailarilik requested changes

2019-08-25 08:21 UTC, ismailarilik commented on sphinx_source/standart_moduller/argparse.rst
> +**NOT:Zorunlu seçimler genellikle kötü form olarak kabul edilir. Çünkü bu paramterler özünde isteğe bağlıdır ve kullanıcılar isteğe bağlı olmasını ister. Mümkün olduğunca kullanmamak gerekir.**
paramterler -> parametreler

2019-08-25 08:22 UTC, ismailarilik commented on sphinx_source/standart_moduller/argparse.rst
> +**NOT:Zorunlu seçimler genellikle kötü form olarak kabul edilir. Çünkü bu paramterler özünde isteğe bağlıdır ve kullanıcılar isteğe bağlı olmasını ister. Mümkün olduğunca kullanmamak gerekir.**
Bu, yapılması gereken son değişiklik. Bundan sonra merge edeceğim değişiklikleri.

2019-08-26 09:07 UTC, ismailarilik approved these changes

2019-08-26 09:07 UTC, merged