Update donguler.rst
yazbel/python pull request #79
Opened 2019-08-30 17:47 UTC by Ksenofanex

Gramer düzeltmesi.

2019-08-31 15:35 UTC, ismailarilik requested changes

2019-08-31 15:35 UTC, ismailarilik commented on sphinx_source/listeler_ve_demetler.rst
> +<http://tr.0wikipedia.org/wiki/Çocuk_oyunları#X_O_X_OYUNU>`_ adresinden de
Bunu böyle yapmayalım; Wikiwand eklentisini kullananlar da olabilir.

2019-09-02 12:15 UTC, Ksenofanex commented
@ismailarilik Düzelttim.

2019-09-03 07:16 UTC, ismailarilik approved these changes

2019-09-03 07:16 UTC, merged