Patch 11
yazbel/python pull request #85
Opened 2019-09-27 14:58 UTC by Ksenofanex

2019-09-28 08:04 UTC, ismailarilik requested changes

2019-09-28 08:04 UTC, ismailarilik commented on sphinx_source/fonksiyonlar.rst
> +Bu fonksiyonun tanımını ve çağrısını eksiksiz bir program içinde gösterelim::
"çağrısını"daki "nı" eki "tanımı" sözcüğüne de eklenmiş oluyor burada "ve"den dolayı. Bu sebeple bu değişikliğe gerek olduğunu düşünmüyorum.

2019-09-28 08:04 UTC, ismailarilik commented on sphinx_source/katkida_bulunanlar.rst
> +    - Fonksiyonlar kısmındaki gramer hatası düzeltildi.
Yukarıda yazdığım yorumun sonucuna bağlı olarak silinmesi gerekebilir.

2019-09-28 09:58 UTC, Ksenofanex commented on sphinx_source/fonksiyonlar.rst
> +Bu fonksiyonun tanımını ve çağrısını eksiksiz bir program içinde gösterelim::
Sorun "nı" ekinde değil. "Bu fonksiyon" kısmında. Çünkü şöyle oluyor;

Bu fonksiyon tanımını ve çağrısını gösterelim:

Anlatım bozukluğu var yukarıda. Doğrusu benim yazdığım şekilde:

"Bu fonksiyonun" tanımını ve çağrısını gösterelim:

2019-09-29 10:12 UTC, ismailarilik requested changes

2019-09-29 10:12 UTC, ismailarilik commented on sphinx_source/fonksiyonlar.rst
> +Bu fonksiyonun tanımını ve çağrısını eksiksiz bir program içinde gösterelim::
Anladım. Öyle olsa bile şu değişikliği yapmaya gerek yok:

"tanımı" -> "tanımını"

2019-09-29 11:17 UTC, Ksenofanex commented on sphinx_source/fonksiyonlar.rst
> +Bu fonksiyonun tanımını ve çağrısını eksiksiz bir program içinde gösterelim::
Var, hâlâ anlatım bozukluğu oluyor yazdığınız şekilde: 

"Bu fonksiyonun" tanımı ve çağrısını gösterelim: kulağa ve göze tuhaf geliyor. Bu kullanım genelde günlük hayatta, konuşma ağzında, iyelik eklerinin düşürülmesiyle kullanılır ama yanlıştır.

Doğru kullanım şekli yazdığım gibi:

"Bu fonksiyonun" tanımını ve çağrısını gösterelim:

2019-09-30 07:32 UTC, ismailarilik commented
Bununla ilgili bir kaynak gösterebilir misiniz? Bir ya da birden fazla isim
arasında iyelik eki paylaşılabilir diye biliyorum.

29 Eyl 2019 Paz 14:17 tarihinde Ksenofanex <notifications@github.com> şunu
yazdı:

> *@Ksenofanex* commented on this pull request.
> ------------------------------
>
> In sphinx_source/fonksiyonlar.rst
> <https://github.com/yazbel/python-istihza/pull/85#discussion_r329349729>:
>
> > @@ -649,7 +649,7 @@ Yukarıda tanımladığımız fonksiyonu nasıl çağıracağımızı biliyorsun
>
>
>
>      sistem_bilgisi_göster()
>
>
>
> -Bu fonksiyon tanımı ve çağrısını eksiksiz bir program içinde gösterelim::
>
> +Bu fonksiyonun tanımını ve çağrısını eksiksiz bir program içinde gösterelim::
>
>
> Var, hâlâ anlatım bozukluğu oluyor yazdığınız şekilde:
>
> "Bu fonksiyonun" tanımı ve çağrısını gösterelim: kulağa ve göze tuhaf
> geliyor. Bu kullanım genelde günlük hayatta, konuşma ağzında, iyelik
> eklerinin düşürülmesiyle kullanılır ama yanlıştır.
>
> Doğru kullanım şekli yazdığım gibi:
>
> "Bu fonksiyonun" tanımını ve çağrısını gösterelim:
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/yazbel/python-istihza/pull/85?email_source=notifications&email_token=AEGFHYL3WWEGDZNLYKWPW5LQMCFFNA5CNFSM4I3HO7TKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCGIHIGI#discussion_r329349729>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEGFHYLQ2VKSLDQYUJSROXDQMCFFNANCNFSM4I3HO7TA>
> .
>

2019-09-30 08:16 UTC, Ksenofanex commented
İyelik eki yalnızca tamlamayla uyumlu olduğu sürece paylaşılabilir. Mesela yukarıdaki örnekteki kelimelerin yerini değiştirerek anlatayım:

Bu fonksiyonun çağrısı ve tanımını gösterelim:

"Çağrısı" tamlamayla kendi başına uyumsuz olduğu için, iyelik eki almadan anlam kayması ve anlatım bozukluğu yaratıyor.

2019-09-30 10:43 UTC, merged