Patch 12
yazbel/python pull request #86
Opened 2019-09-30 12:56 UTC by Ksenofanex

2019-09-30 15:23 UTC, Ksenofanex commented
Nesne tabanli programlama'daki düzeltme yanlış oldu, benim hatam. Test yaparken dalgınlıkla commit attım.

2019-10-01 08:10 UTC, ismailarilik requested changes

2019-10-01 08:10 UTC, ismailarilik commented on sphinx_source/moduller.rst
> +bütün içeriğini olduğu gibi masaüstüne atmaya benzetebilirsiniz. Böyle bir
"açmaya" daha uygun gibi, çünkü burada bir arşivi bir dizine açmaktan bahsediliyor. "atmak" daha çok kesip yapıştırmak manasına uygun düşüyor gibi.

2019-10-01 09:05 UTC, Ksenofanex commented on sphinx_source/moduller.rst
> +bütün içeriğini olduğu gibi masaüstüne atmaya benzetebilirsiniz. Böyle bir
"sıkıştırılmış bir klasörün bütün içeriğini olduğu gibi masaüstüne açmaya benzetebilirsiniz. Böyle bir durumda, eğer masaüstünde sıkıştırılmış klasördekilerle aynı adlı dosyalar varsa, sıkıştırılmış klasör içindeki dosya adları, masaüstünde halihazırda varolan dosya adlarıyla çakışacaktır."

2019-10-02 08:38 UTC, ismailarilik commented on sphinx_source/moduller.rst
> +bütün içeriğini olduğu gibi masaüstüne atmaya benzetebilirsiniz. Böyle bir
Bu yorumda söylemek istediğinizi anlamadım maalesef.

2019-10-02 09:36 UTC, Ksenofanex commented on sphinx_source/moduller.rst
> +bütün içeriğini olduğu gibi masaüstüne atmaya benzetebilirsiniz. Böyle bir
Mesajın tamamını kopyalayıp yapıştırdım. Tamamı okunduğunda, masaüstüne "atmak" kast edildiği görülebiliyor.

2019-10-03 08:09 UTC, ismailarilik approved these changes

2019-10-03 08:09 UTC, merged